# Generated by Django 4.2 on 2023-05-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.medtype'),
        ),
    ]
